# Created by forg3
# License: MIT
#
# Samba Performance Profile (Linux server side)
#
# SMB Speed Doctor diagnoses the client; this script tunes the SERVER.
# Generates a [smb-speed-doctor] block ready for /etc/samba/smb.conf with:
#   - TCP_NODELAY + IPTOS_THROUGHPUT: lower copy latency
#   - AIO enabled: asynchronous I/O for large workloads
#   - server multi channel support: aggregates NICs on server (Samba 4.4+)
#   - short deadtime: frees zombie connections
#
# USAGE:
#   sudo ./Optimize-SambaServer.ps1 -Status            # show current config
#   sudo ./Optimize-SambaServer.ps1 -Apply             # backup + apply + reload
#   sudo ./Optimize-SambaServer.ps1 -Rollback          # restore backup
#   sudo ./Optimize-SambaServer.ps1 -Apply -NicCount 2 # declare 2 NICs for multichannel
#
# EXECUTES ON LINUX (pwsh) — requires root and Samba installed.

[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [switch]$Apply,
    [switch]$Rollback,
    [switch]$Status,
    [int]$NicCount = 0   # 0 = auto-detects physical interfaces UP
)

$ErrorActionPreference = 'Stop'

if ($IsWindows) { throw "This script runs on LINUX server (Samba). On Windows Server, use native Set-SmbServerConfiguration cmdlets." }

$SmbConf = '/etc/samba/smb.conf'
$BackupFile = '/var/lib/smb-speed-doctor/smb.conf.pre-doctor'

function Assert-Root {
    if ((id -u) -ne 0) { throw "Execute as root (sudo)." }
}

function Get-PhysicalNics {
    (ip -brief link show | Select-String 'UP' | ForEach-Object {
        ($_.Line -split '@')[0].Trim() -split '\s+' | Select-Object -First 1
    }) | Where-Object { $_ -notmatch 'lo|tailscale|docker|veth|br-|tun|tap' }
}

if ($Status -or (-not $Apply -and -not $Rollback)) {
    Write-Host "=== SAMBA SERVER — STATUS ===" -ForegroundColor Cyan
    testparm -s 2>/dev/null | Select-String 'server multi channel|socket options|aio|deadtime|max protocol|server min protocol|read raw|write raw'
    Write-Host "`nPhysical interfaces UP: $((Get-PhysicalNics) -join ', ')"
    return
}

Assert-Root

if (-not (Test-Path $SmbConf)) { throw "$SmbConf not found — is Samba installed?" }

if ($Apply) {
    if (-not (Test-Path '/var/lib/smb-speed-doctor')) { New-Item -ItemType Directory -Path '/var/lib/smb-speed-doctor' | Out-Null }
    Copy-Item $SmbConf $BackupFile -Force
    Write-Host "Backup: $BackupFile"

    # Multichannel: requires >= 2 real NICs to make sense
    $nics = if ($NicCount -gt 0) { $NicCount } else { @(Get-PhysicalNics).Count }
    $multichannel = if ($nics -ge 2) { 'yes' } else { 'no' }

    $block = @"

# --- Block generated by SMB Speed Doctor ($(Get-Date -Format o)) ---
# Rollback: sudo cp '$BackupFile' '$SmbConf' && systemctl restart smbd
[global]
    # Tuning for large copies (SMB Speed Doctor roadmap)
    socket options = TCP_NODELAY IPTOS_THROUGHPUT SO_RCVBUF=131072 SO_SNDBUF=131072
    aio read size = 16384
    aio write size = 16384
    server multi channel support = $multichannel
    deadtime = 10
    getwd cache = yes
    # End of SMB Speed Doctor block
"@

    if ($PSCmdlet.ShouldProcess($SmbConf, "Add tuning block")) {
        # Idempotent: removes previous blocks before inserting
        $content = Get-Content $SmbConf -Raw
        $content = $content -replace "(?ms)\r?\n# --- Block generated by SMB Speed Doctor.*?# End of SMB Speed Doctor block\r?\n", "`n"
        Add-Content -Path $SmbConf -Value $block -Encoding UTF8

        # Validate BEFORE reload: broken conf must not crash service
        $testOut = testparm -s 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Host "ERROR: invalid smb.conf after editing! Rolling back..." -ForegroundColor Red
            Copy-Item $BackupFile $SmbConf -Force
            throw $testOut
        }

        systemctl reload smbd
        Write-Host "Applied. multichannel=$multichannel ($nics NIC(s)). smbd reloaded." -ForegroundColor Green
        if ($nics -lt 2) {
            Write-Host "WARNING: multichannel disabled — only $nics physical NIC(s) present." -ForegroundColor Yellow
        }
        Write-Host "`nValidate from client:"
        Write-Host "  smbdoctor-cli scan --save before.json --path \\$(hostname)\share"
    }
    return
}

if ($Rollback) {
    if (-not (Test-Path $BackupFile)) { throw "No backup found in $BackupFile." }
    Copy-Item $BackupFile $SmbConf -Force
    testparm -s 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "Backup restored but smb.conf is invalid — review manually!" }
    systemctl reload smbd
    Remove-Item $BackupFile -Force
    Write-Host "Reverted to previous state. smbd reloaded." -ForegroundColor Green
}
